FROM node:20-alpine AS base

# Install pnpm
RUN npm install -g pnpm

WORKDIR /usr/src/app

# Add ARG for environment variables
ARG DATABASE_URL
ARG JWT_SECRET

# Copy necessary files for dependency installation
COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/ws ./apps/ws

# Install global Prisma CLI
RUN npm install -g prisma@6.5.0

# Install dependencies
RUN pnpm install --frozen-lockfile

# Change to the packages/db directory and generate Prisma client
WORKDIR /usr/src/app/packages/db
RUN prisma generate

# Change back to the root directory
WORKDIR /usr/src/app

# Set environment variables
ENV DATABASE_URL=${DATABASE_URL}
ENV JWT_SECRET=${JWT_SECRET}
ENV WS_PORT=8080

# Build the websocket service
WORKDIR /usr/src/app/apps/ws
RUN pnpm run build

# Expose the port
EXPOSE 8080

# Start the ws service
CMD ["node", "dist/index.js"]