FROM node:20-alpine AS base

# Install pnpm
RUN npm install -g pnpm

WORKDIR /usr/src/app

# Add ARG for environment variables
ARG DATABASE_URL
ARG JWT_SECRET
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_WS_URL

# Copy necessary files for dependency installation
COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/collabydraw ./apps/collabydraw

# Install global Prisma CLI
RUN npm install -g prisma@6.5.0

# Install dependencies
RUN pnpm install --frozen-lockfile

# Change to the packages/db directory and generate Prisma client
WORKDIR /usr/src/app/packages/db
RUN prisma generate

# Change back to the root directory
WORKDIR /usr/src/app

# Set environment variables
ENV DATABASE_URL=${DATABASE_URL}
ENV JWT_SECRET=${JWT_SECRET}
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
ENV NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
ENV PORT=3000

# Create .env.local for Next.js
WORKDIR /usr/src/app/apps/collabydraw
RUN echo "JWT_SECRET=$JWT_SECRET" > .env.local
RUN echo "DATABASE_URL=$DATABASE_URL" >> .env.local

# Change back to the root directory
WORKDIR /usr/src/app

# Build only the Next.js application
RUN DATABASE_URL=${DATABASE_URL} JWT_SECRET=${JWT_SECRET} NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL} NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL} pnpm run build

# Expose only port 3000
EXPOSE 3000

# Start only Next.js
WORKDIR /usr/src/app/apps/collabydraw
CMD ["pnpm", "run", "start"]